# Generated by Django 4.1.7 on 2023-04-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title_tag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
