# Generated by Django 4.1.7 on 2023-04-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_tag_title_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title_tag',
            new_name='tagname',
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='product.tag'),
        ),
    ]
