# Generated by Django 4.1.7 on 2023-03-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название машины:')),
                ('year', models.CharField(max_length=100, verbose_name='Год выпуска:')),
                ('fuel_type', models.CharField(max_length=100, verbose_name='Топливо: ')),
                ('engine_size', models.CharField(max_length=100, verbose_name='Объем двигателя:')),
                ('transmission', models.CharField(max_length=100, verbose_name='КП')),
                ('body_type', models.CharField(choices=[('Седан', 'Седан'), ('Кросс-овер', 'Кросс-овер'), ('Внедорожник', 'Внедорожник'), ('Универсал', 'Универсал')], max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('seat', models.CharField(max_length=100)),
                ('cost', models.PositiveIntegerField()),
                ('extra_parameters', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
