# Generated by Django 4.1.7 on 2023-03-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ваше имя:')),
                ('lastname', models.CharField(max_length=100, verbose_name='Ваша фамилия:')),
                ('email', models.CharField(max_length=100, verbose_name='Ваш e-mail:')),
                ('feedback_text', models.TextField(max_length=200, verbose_name='Ваш отзыв:')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Седан', 'Седан'), ('Кросс-овер', 'Кросс-овер'), ('Внедорожник', 'Внедорожник'), ('Универсал', 'Универсал')], max_length=100, verbose_name='Тип кузова: '),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.CharField(max_length=100, verbose_name='Объем двигателя: '),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.CharField(max_length=100, verbose_name='Мощность двигателя: '),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(max_length=100, verbose_name='КП: '),
        ),
    ]
