# Generated by Django 4.1.7 on 2023-03-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_carreview_user_alter_car_body_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreview',
            name='car_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_object', to='car.car'),
        ),
        migrations.AddField(
            model_name='carreview',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='carreview',
            name='rate_stars',
            field=models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='carreview',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
